apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
spec:
  selector:
    matchLabels:
      app: downloader
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
        - name: downloader
          image: @docker.registry.uri@/@docker.image.name@
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/video/downloads
              name: downloads
            - mountPath: /var/log/downloader
              name: logs
      volumes:
        - name: downloads
          hostPath:
            path: /youtube-trimmer/video/downloads
            type: Directory
        - name: logs
          hostPath:
            path: /youtube-trimmer/logs/downloader
            type: Directory