spring:
  datasource:
    url: jdbc:mysql://localhost/youtube_trimmer?user=root&password=root

authentication:
  token:
    signing-key-path: ${user.home}/youtube-trimmer/key
    expiration-duration: 7   # Days

---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:mysql://mysql/youtube_trimmer?user=root&password=root
  rabbitmq:
    host: rabbitmq

authentication:
  token:
    signing-key-path: /app/secret/key

storage:
  video-container-name: trimmed
  connection-string-path: /secret/azurestorageconnectionstring
  sas-token-expiry-duration-days: 2
  download-url-base: https://youtubetrimmer.blob.core.windows.net
