spring:
  datasource:
    url: jdbc:mysql://localhost/youtube_trimmer?user=root&password=root

authentication:
  token:
    signing-key-path: ${user.home}/youtube-trimmer/key
    expiration-duration: 7   # Days
