spring:
  datasource:
    url: jdbc:mysql://localhost/youtube_trimmer?user=root&password=root

trimmer:
  working-directory: ${user.home}/youtube-trimmer/trimmer
  output-directory: ${user.home}/youtube-trimmer/trimmed