spring:
  datasource:
    url: jdbc:mysql://localhost/youtube_trimmer?user=root&password=root

trimmer:
  working-directory: ${user.home}/youtube-trimmer/trimmer
  process-logs-directory: ${user.home}/youtube-trimmer/logs/trimmer/process
storage:
  video-container-name: trimmed
  connection-string-path: ${user.home}/youtube-trimmer/secret/azurestorageconnectionstring
---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:mysql://mysql/youtube_trimmer?user=root&password=root
  rabbitmq:
    host: rabbitmq

trimmer:
  working-directory: /app/workdir
  process-logs-directory: /var/log/trimmer/process

storage:
  connection-string-path: /secret/azurestorageconnectionstring