apiVersion: apps/v1
kind: Deployment
metadata:
  name: trimmer
spec:
  selector:
    matchLabels:
      app: trimmer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trimmer
    spec:
      containers:
        - name: trimmer
          image: @docker.registry.uri@/@docker.image.name@
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/video/downloads
              name: downloads
            - mountPath: /var/log/trimmer
              name: logs
            - mountPath: /data/video/trimmed
              name: trimmed
            - mountPath: /secret
              name: secret
      volumes:
        - name: downloads
          azureFile:
            secretName: storage-secret
            shareName: youtube-trimmer/video/downloads
            readOnly: false
        - name: logs
          azureFile:
            secretName: storage-secret
            shareName: youtube-trimmer/logs/trimmer
            readOnly: false
        - name: trimmed
          azureFile:
            secretName: storage-secret
            shareName: youtube-trimmer/video/trimmed
            readOnly: false
        - name: secret
          secret:
            secretName: storage-secret