apiVersion: apps/v1
kind: Deployment
metadata:
  name: trimmer
spec:
  selector:
    matchLabels:
      app: trimmer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trimmer
    spec:
      containers:
        - name: trimmer
          image: @docker.registry.uri@/@docker.image.name@
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/video/downloads
              name: downloads
            - mountPath: /var/log/trimmer
              name: logs
            - mountPath: /data/video/trimmed
              name: trimmed
      volumes:
        - name: downloads
          hostPath:
            path: /youtube-trimmer/video/downloads
            type: Directory
        - name: logs
          hostPath:
            path: /youtube-trimmer/logs/trimmer
            type: Directory
        - name: trimmed
          hostPath:
            path: /youtube-trimmer/video/trimmed
            type: Directory