apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
      volumes:
        - name: init
          azureFile:
            secretName: storage-secret
            shareName: youtube-trimmer/mysql/init
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
#  type: ClusterIP
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
