apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /docker-entrypoint-initdb.d
              name: init
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
      volumes:
        - name: data
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Bojan/youtube-trimmer/kubernetes/mysql/data
            type: Directory
        - name: init
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Bojan/youtube-trimmer/kubernetes/mysql/init
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
