spring:
  datasource:
    url: jdbc:mysql://localhost/youtube_trimmer?user=root&password=root

downloader:
  working-directory: ${user.home}/youtube-trimmer/downloader
  video-directory: ${user.home}/youtube-trimmer/downloads